#!/bin/bash
#Data alteração 20252

echo -e "#REV. 1"

sleep 1 &&
echo -e "" &&
echo -e "" &&
echo -e "" &&
echo -e "****************" &&
echo -e "Termino do XX.sh" &&
echo -e "****************" &&
veianew ;
