#!/bin/bash
#########################################
#########################################
###          SCRIPT VEIANEW           ###
###          DATE 18/11/2020          ###
###              20323                ###
#########################################
#############MCARVALHO###################
#############RAZARIAS####################
#Variaveis de Versao e idioma
export VERSION_VN="v5.8.5"
#export VERSION_VN="v5.3.42_BETA"
export LANG=pt_BR

#Variavel de Cores
export Cor_Preto="\033[0m"
export Cor_Vermelho="\033[1;31m"
export Cor_VerdeClaro="\033[1;32m"
export Cor_Amarelo="\033[1;33m"
export Cor_Fundo_Cinza="\033[47;1;37m"

#Variaveis de diretorio root e veianew.ini
export dirRoot="/bin"
export veianewIni="${dirRoot}/veianew.ini"

#Variaveis de caminho de diretorios
export PATH_COMUM="/Zanthus/Zeus/path_comum"
###export SERVER_VN="${PATH_COMUM}/0.66"
###export SERVER_VN_MANAGER="${SERVER_VN}/MANAGER"
###export SERVER_VN_MODULOPHPPDV="${SERVER_VN}/MODULOPHPPDV"
###export SERVER_VN_SCRIPTS_VEIANEW="${SERVER_VN}/SCRIPTS_VEIANEW"
###export SERVER_VN_MODULO_COMPILADO="${SERVER_VN_SCRIPTS_VEIANEW}/MODULO_COMPILADO"
export APACHE2="/usr/local/apache22"
export HTDOCS="${APACHE2}/htdocs"
export MANAGER="${HTDOCS}/manager"
export FTP_COMPLEMENTARES="200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares"
export VEIANEW="${APACHE2}/VEIANEW"

export DIR_BKP="${SERVER_VN_MANAGER}"
export DESTINO_BKP="${SERVER_VN_MANAGER}"
export DIR_BKPMODULO="${SERVER_VN_MODULOPHPPDV}"
export DESTINO_BKPMODULO="${SERVER_VN_MODULOPHPPDV}"

unset MANAGER_USO
export MANAGER_USO=`ls -a ${HTDOCS}/.*anager*.zip.TEMP | sed "s#${HTDOCS}/.##" | sed 's/.TEMP//'`

#Iniciando funcionalidades na tela
echo -e "${Cor_Preto}"
echo -e "${Cor_FundoCinza}${Cor_Vermelho}${VERSION_VN}${Cor_Preto}"

if [ -d "${MANAGER}" ] ; then
echo -e "${MANAGER} Já existe"
else
mkdir "${MANAGER}" & chmod 777 "${MANAGER}"
fi

#if [ -d "${SERVER_VN}" ] ; then
#umount "${SERVER_VN}"
#else
#mkdir "${SERVER_VN}" & chmod 777 "${SERVER_VN}"
#fi
#
#if [ -d "${SERVER_VN_MANAGER}" ] ; then
#umount "${SERVER_VN_MANAGER}" &
#else
#mkdir "${SERVER_VN_MANAGER}" & chmod 777 "${SERVER_VN_MANAGER}" &
#fi
#
#if [ -d "${SERVER_VN_MODULOPHPPDV}" ] ; then
#umount "${SERVER_VN_MODULOPHPPDV}"
#else
#mkdir "${SERVER_VN_MODULOPHPPDV}" & chmod 777 "${SERVER_VN_MODULOPHPPDV}" &
#fi
#
#if [ -d "${SERVER_VN_SCRIPTS_VEIANEW}" ] ; then
#umount "${SERVER_VN_SCRIPTS_VEIANEW}"
#else
#mkdir "${SERVER_VN_SCRIPTS_VEIANEW}" & chmod 777 "${SERVER_VN_SCRIPTS_VEIANEW}" &
#fi
#
#if [ -d "${SERVER_VN_MODULO_COMPILADO}" ] ; then
#umount "${SERVER_VN_MODULO_COMPILADO}"
#else
#mkdir "${SERVER_VN_MODULO_COMPILADO}" & chmod 777 "${SERVER_VN_MODULO_COMPILADO}" &
#fi
#
if [ -d "${PATH_COMUM}" ] ; then
umount "${PATH_COMUM}"
else
mkdir "${PATH_COMUM}" & chmod 777 "${PATH_COMUM}" &
fi

if [ -e "${VEIANEW}/history.vnw" ] ; then
sleep 0 &
else
echo ' ' > "${VEIANEW}/history.vnw" &
chmod 777 "${VEIANEW}/history.vnw" &
fi

if [ -e "${VEIANEW}/history_all.vnw" ] ; then
sleep 0 &
else
echo ' ' > "${VEIANEW}/history_all.vnw" &
chmod 777 "${VEIANEW}/history_all.vnw" &
fi



# rsantos INICIO
##atualizaSenha(){
##  echo "INFORME SEU USUARIO E SENHA DE ACESSO AO '192.168.0.97'"
#  echo -ne "USUARIO: "
#  read USUARIO
#  echo -ne "SENHA: "
#  read SENHA
#  echo "USUARIO=${USUARIO}" >  ${veianewIni}
#  echo "SENHA=${SENHA}"     >> ${veianewIni}
#}
#montar15(){
#  ##SERVIDOR1='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Manager'
#  SERVIDOR1='192.168.0.66/publico/qualidade/VERSOES/Manager'
#  export COMANDO1="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR1} ${SERVER_VN_MANAGER}"
#  ${COMANDO1}
#
#  ##SERVIDOR2='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/moduloPHPPDV'
#  SERVIDOR2='192.168.0.66/publico/qualidade/VERSOES/moduloPHPPDV'
#  export COMANDO2="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR2} ${SERVER_VN_MODULOPHPPDV}"
#
#  ##SERVIDOR3='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Scripts_veianew'
#  SERVIDOR3='192.168.0.66/publico/qualidade/VERSOES/Scripts_veianew'
#  export COMANDO3="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR3} ${SERVER_VN_SCRIPTS_VEIANEW}"
#
#  ##SERVIDOR4='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Scripts_veianew/Modulo_Compilado'
#  SERVIDOR4='192.168.0.66/publico/qualidade/VERSOES/Scripts_veianew/Modulo_Compilado'
#  export COMANDO4="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR4} ${SERVER_VN_MODULO_COMPILADO}"
#
#  return $?
#}
#if [ -e "${veianewIni}" ]
#then
# . ${veianewIni}
#else
#  atualizaSenha
#fi
#montar15
#if [ ${?} -ne "0" ]
#then
#  OPC=0
#  while [ ${OPC} -ne 1 -a ${OPC} -ne 2 ]
#  do
#    echo -e  "NÃO FOI POSSIVEL MONTAR O CAMINHO //${SERVIDOR1} UTILIZANDO O COMANDO ABAIXO\n (${COMANDO1})"
#    echo     "O QUE VOCE DESEJA FAZER?"
#    echo     "1. PROSSEGUIR SEM MONTAR (utilizar versoes copiadas anteriormente)"
#    echo     "2. ATUALIZAR USUARIO E SENHA DE ACESSO AO '192.168.0.97'"
#    echo -ne "OPCAO: "
#    read     OPC
#    case ${OPC} in
#      1)
#        echo "PROSSEGUINDO ..."
#      ;;
#      2)
#        atualizaSenha
#        montar15
#        [ $? -ne 0 ] && OPC=0
#      ;;
#      *)
#        echo "DIGITE UMA OPCAO VALIDA!"
#      ;;
#    esac
#  done
#fi
## rsantos FIM
#
#${COMANDO3}
#IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
#echo -e "${HOSTNAME}" "   -   " "${IP}" "   -   " "$(date +%d/%m/%y__%H:%M:%S)" "   -   " "${VERSION_VN}" >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVN/${HOSTNAME}.VNL;

sleep 0
echo -e "Carregando..."
sleep 1

#umount ${SERVER_VN_SCRIPTS_VEIANEW}

#rsync -uvt ${SERVER_VN_MANAGER}/php*.zip ${HTDOCS} &&

#if [ -d ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" ] ; then
#echo -e "Diretorio de Backup já existe."
#else
#mkdir ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" & chmod 777 ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" &
#fi

#if [ -e "${VEIANEW}/history_all.vnw" ] ; then
# se existir mais de 45 pacotes manager no htdocs
#rodar a opção BKP, quardando os mais antigos
#sleep 0 &
#else
#segue o script
#fi


cd ${HTDOCS}/
for arquivo in *.ZIP
do
newname=$(basename ${arquivo} ZIP)zip
mv ${arquivo} ${newname}
done

cd ${HTDOCS}/

chown root.root ${HTDOCS}/*
chmod 777 ${HTDOCS}/*.zip

for file in *anager*.zip

do
   if [ ! "${file}" = `echo "${file}"|sed "s/ /_/g"` ]; then
   mv "${file}" `echo "${file}"|sed "s/ /_/g"`
   fi
done

find . -name "*anager*.zip"
rm -rf ${HTDOCS}/copie_um_pacote_manager_para_o_htdocs.zip

ListaArquivos(){
if [ `find . -name '*anager*.zip' | wc -l` -gt 0 ]; then
clear; i=1

echo -e "#     ${Cor_Amarelo} OPÇÕES\t\b\b********************************  PACOTES  MANAGER  ********************************${Cor_Preto}"
CASE='case $opt in'
for arq in `ls -1tr *anager*.zip`
do
    echo -e "#\t\b\b\b\b$i    ${arq}"
    CASE="${CASE}
  $i) ${APACHE2}/bin/apachectl stop ; rm -rf ${HTDOCS}/*.zip.TEMP ; rsync -uv ${HTDOCS}/\"${arq}\" ${MANAGER} && unzip -oq ${MANAGER}/\"${arq}\" -d ${MANAGER} && touch ${HTDOCS}/\".${arq}.TEMP\" && echo -e '#\tEXTRACAO CONCLUIDA' && chown -R zanthus.zanthus * && chmod -R 777 * && ${APACHE2}/bin/apachectl start && mkdir ${MANAGER}/Logs && chown -R zanthus.zanthus ${MANAGER}/Logs/ ; sleep 1 ;;"
  i=$((i+1))
done

CASE="${CASE}

   99) ${VEIANEW}/99.sh ;;
   98) ${VEIANEW}/98.sh ;;
   97) ${VEIANEW}/97.sh ;;

   89) ${VEIANEW}/89.sh ;;
   88) ${VEIANEW}/88.sh ;;
   87) ${VEIANEW}/87.sh ;;

   79) ${VEIANEW}/79.sh ;;
   78) ${VEIANEW}/78.sh ;;
   77) ${VEIANEW}/77.sh ;;

   69) ${VEIANEW}/69.sh ;;
   68) ${VEIANEW}/68.sh ;;
   67) ${VEIANEW}/67.sh ;;

   66) ${VEIANEW}/66.sh ;;
   65) ${VEIANEW}/65.sh ;;
   64) ${VEIANEW}/64.sh ;;

   59) ${VEIANEW}/59.sh ;;
   599) ${VEIANEW}/599.sh ;;
   58) ${VEIANEW}/58.sh ;;
   57) ${VEIANEW}/57.sh ;;
   56) ${VEIANEW}/56.sh ;;
   55) ${VEIANEW}/55.sh ;;
   54) ${VEIANEW}/54.sh ;;
   53) ${VEIANEW}/53.sh ;;
   52) ${VEIANEW}/52.sh ;;
   51) ${VEIANEW}/51.sh ;;
   50) ${VEIANEW}/50.sh ;;
   49) ${VEIANEW}/49.sh ;;
   48) ${VEIANEW}/48.sh ;;

   09) ${VEIANEW}/09.sh ;;
   08) ${VEIANEW}/08.sh ;;
   07) ${VEIANEW}/07.sh ;;
   06) ${VEIANEW}/06.sh ;;
   05) ${VEIANEW}/05.sh ;;
   04) ${VEIANEW}/04.sh ;;
   03) ${VEIANEW}/03.sh ;;
   02) ${VEIANEW}/02.sh ;;
   01) ${VEIANEW}/01.sh ;;
   00) ${VEIANEW}/00.sh ;;

   01B) ${VEIANEW}/01B.sh ;;
   9999) ${VEIANEW}/9999.sh ;;
   BKP) ${VEIANEW}/BKP.sh ;;
   *) echo 'OPÇÃO INVÁLIDA! TENTE NOVAMENTE'; sleep 2; clear; ListaArquivos;;
esac"

echo -e ""
echo -e "#\t${Cor_Amarelo}\b\b\b\bMANAGER EM USO: ${Cor_Vermelho} ${MANAGER_USO}"
echo -e "${Cor_Preto}"
#echo -e "\t\t***** APACHE *****                           ***** MIRAGE *****                  ***** NODE *****"
echo -e "#\t\b\b\b\b99    START     APACHE               89    START     MIRAGE              79    START     NODE"
echo -e "#\t\b\b\b\b98    STOP      APACHE               88    STOP      MIRAGE              78    STOP      NODE"
echo -e "#\t\b\b\b\b97    RESTART   APACHE               87    RESTART   MIRAGE              77    RESTART   NODE"
echo -e ""
#echo -e "\t\t***** APACHE / MIRAGE *****                                  ***** APACHE / MIRAGE / NODE *****"
echo -e "#\t\b\b\b\b69    START     APACHE e MIRAGE                          66   START     APACHE, MIRAGE e NODE"
echo -e "#\t\b\b\b\b68    STOP      APACHE e MIRAGE                          65   STOP      APACHE, MIRAGE e NODE"
echo -e "#\t\b\b\b\b67    RESTART   APACHE e MIRAGE                          64   RESTART   APACHE, MIRAGE e NODE"
echo -e ""
echo -e "#\t\b\b\b\b59    LIMPAR DIRETÓRIO MANAGER + COPIAR CERTIFICADO + ZMWSInfo"
echo -e "#\t\b\b\b\b599   EXCLUI PACOTES MANAGER +20 DIAS DO 'HTDOCS'"
echo -e "#\t\b\b\b\b58    ZMWSInfo COM LOG"
echo -e "#\t\b\b\b\b57    ZMWSInfo SEM LOG"
echo -e "#\t\b\b\b\b56    ZMWSInfo COM LOG FULL                                 09    CP MANAGER OFICIAL"
echo -e "#\t\b\b\b\b55    FAZER BACKUP CERTIFICADO                              08    CP ZEUSMANAGER.ZLG HOJE P/ PATH_COMUM"
echo -e "#\t\b\b\b\b54    LIMPAR LOGS ../MANAGER                                07    ZERA CONTEUDO ZEUSMANAGER.ZLG HOJE"
echo -e "#\t\b\b\b\b53    LIMPAR LOGS ../HTDOCS                                 06    WGET BIBLIOTECAS FTP > PATH_COMUM"
echo -e "#\t\b\b\b\b51    ATIVAR 'INSPEC_ELEMENTO' E 'CHECK_JS'                 04    REINICIAR MEMCACHED"
echo -e "#\t\b\b\b\b50    ATIVAR 'DEBUG_CLAZ'                                   03    ATUALIZAR BIBLIOTECA"
echo -e "#\t\b\b\b\b49    DESATIVAR INSPEC_ELEMENTO CHECK_JS DEBUG_CLAZ         01    ATUALIZAR VEIANEW"
echo -e "#\t\b\b\b\b48    PERMISSÃO DIRETORIO 'ARQUIVOS'                        00    SAIR"
echo -e "#\t\b\b\b\b                                                                              ${Cor_FundoCinza} ${Cor_Vermelho} ${VERSION_VN} ${Cor_Pret#!/bin/bash
#Data alteração 20005

echo -e 'Aguarde, conectando no ftp.zanthus.com.br' &&
echo -e 'Atualizando bibliotecas para o PATH_COMUM!!!' &&
sleep 3 &&
wget -N --tries=2 -P ${PATH_COMUM}/so/ ftp://${FTP_COMPLEMENTARES}/so/*  &&
wget -N --tries=2 -P ${PATH_COMUM}/so_co5 ftp://${FTP_COMPLEMENTARES}/so_co5/*  &&
wget -N --tries=2 -P ${PATH_COMUM}/so_r64 ftp://${FTP_COMPLEMENTARES}/so_r64/*  &&
wget -N --tries=2 -P ${PATH_COMUM}/so_u64 ftp://${FTP_COMPLEMENTARES}/so_u64/*  &&
wget -N --tries=2 -P ${PATH_COMUM}/so_ubu ftp://${FTP_COMPLEMENTARES}/so_ubu/*  &&
sleep 1 &&
echo -e "" &&
echo -e "" &&
echo -e "" &&
echo -e "****************" &&
echo -e "Termino do 06.sh" &&
echo -e "****************" &&
veianew ;o}"
echo -ne "#${Cor_Amarelo}"
sed ':a;$!N;s/\n//;ta;' ${VEIANEW}/history.vnw

echo -ne "${Cor_Preto}#${Cor_VerdeClaro}   INFORME A OPÇÃO DESEJADA: "
read -p "" opt

sed -i '1 i'${opt}'  ' ${VEIANEW}/history_all.vnw
sed -n '1,7p' ${VEIANEW}/history_all.vnw > ${VEIANEW}/history.vnw
sed -i '1s/^/           HISTORICO DE USO: /' ${VEIANEW}/history.vnw

echo -e "${Cor_Preto}"
eval "${CASE}"

else
clear
echo -e "#\n#\n#\t NÃO HA PACOTES DO MANAGER DISPONIVEIS PARA EXTRAÇÃO\n#\n#"
echo -e "#\n#\n#\t COPIE UM PACOTE DO MANAGER PARA O HTDOCS\n#\n#"
touch ${HTDOCS}/copie_um_pacote_manager_para_o_htdocs.zip
sleep 5
clear
fi
}

ListaArquivos
