#!/bin/bash
#########################################
#########################################
###          SCRIPT VEIANEW           ###
###          DATE 27/12/2019          ###
#########################################
#############MCARVALHO###################
#############RAZARIAS####################
#Variaveis de Versao e idioma
export VERSION_VN="v5.0.21_BETA"
export LANG=pt_BR

#Variavel de Cores
export Cor_Preto="\033[0m"
export Cor_Vermelho="\033[1;31m"
export Cor_VerdeClaro="\033[1;32m"
export Cor_Amarelo="\033[1;33m"
export Cor_Fundo_Cinza="\033[47;1;37m"

#Variaveis de diretorio root e veianew.ini
export dirRoot="/bin"
export veianewIni="${dirRoot}/veianew.ini"

#Variaveis de caminho de diretorios
export PATH_COMUM="/Zanthus/Zeus/path_comum"
export SERVER_VN="${PATH_COMUM}/0.66"
export SERVER_VN_MANAGER="${SERVER_VN}/MANAGER"
export SERVER_VN_MODULOPHPPDV="${SERVER_VN}/MODULOPHPPDV"
export SERVER_VN_SCRIPTS_VEIANEW="${SERVER_VN}/SCRIPTS_VEIANEW"
export SERVER_VN_MODULO_COMPILADO="${SERVER_VN}/MODULO_COMPILADO"
export APACHE2="/usr/local/apache2"
export HTDOCS="${APACHE2}/htdocs"
export MANAGER="${HTDOCS}/manager"
export FTP_COMPLEMENTARES="200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares"
export VEIANEW="${APACHE2}/VEIANEW"

#Iniciando funcionalidades na tela
echo -e "${Cor_Preto}"
echo -e "${Cor_FundoCinza}${Cor_Vermelho}${VERSION_VN}${Cor_Preto}"

if [ -d "${SERVER_VN}" ] ; then
umount "${SERVER_VN}"
else
mkdir "${SERVER_VN}" & chmod 777 "${SERVER_VN}"
fi

if [ -d "${SERVER_VN_MANAGER}" ] ; then
umount "${SERVER_VN_MANAGER}" &
else
mkdir "${SERVER_VN_MANAGER}" & chmod 777 "${SERVER_VN_MANAGER}" &
fi

if [ -d "${SERVER_VN_MODULOPHPPDV}" ] ; then
umount "${SERVER_VN_MODULOPHPPDV}"
else
mkdir "${SERVER_VN_MODULOPHPPDV}" & chmod 777 "${SERVER_VN_MODULOPHPPDV}" &
fi

if [ -d "${SERVER_VN_SCRIPTS_VEIANEW}" ] ; then
umount "${SERVER_VN_SCRIPTS_VEIANEW}"
else
mkdir "${SERVER_VN_SCRIPTS_VEIANEW}" & chmod 777 "${SERVER_VN_SCRIPTS_VEIANEW}" &
fi

if [ -d "${SERVER_VN_MODULO_COMPILADO}" ] ; then
umount "${SERVER_VN_MODULO_COMPILADO}"
else
mkdir "${SERVER_VN_MODULO_COMPILADO}" & chmod 777 "${SERVER_VN_MODULO_COMPILADO}" &
fi

if [ -d "${PATH_COMUM}" ] ; then
umount "${PATH_COMUM}"
else
mkdir "${PATH_COMUM}" & chmod 777 "${PATH_COMUM}" &
fi

# rsantos INICIO
atualizaSenha(){
  echo "INFORME SEU USUARIO E SENHA DE ACESSO AO '192.168.0.15'"
  echo -ne "USUARIO: "
  read USUARIO_15
  echo -ne "SENHA: "
  read SENHA_15
  echo "USUARIO_15=${USUARIO_15}" >  ${veianewIni}
  echo "SENHA_15=${SENHA_15}"     >> ${veianewIni}
}
montar15(){
  ##SERVIDOR1='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Manager'
  SERVIDOR1='192.168.0.66/publico/qualidade/VERSOES/Manager'
  COMANDO1="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR1} ${SERVER_VN_MANAGER}"
  ${COMANDO1}

  ##SERVIDOR2='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/moduloPHPPDV'
  SERVIDOR2='192.168.0.66/publico/qualidade/VERSOES/moduloPHPPDV'
  COMANDO2="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR2} ${SERVER_VN_MODULOPHPPDV}"

  ##SERVIDOR3='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Scripts_veianew'
  SERVIDOR3='192.168.0.66/publico/qualidade/VERSOES/Scripts_veianew'
  COMANDO3="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR3} ${SERVER_VN_SCRIPTS_VEIANEW}"

  ##SERVIDOR4='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Scripts_veianew/Modulo_Compilado'
  SERVIDOR4='192.168.0.66/publico/qualidade/VERSOES/Scripts_veianew/Modulo_Compilado'
  COMANDO4="mount -t cifs -s -o username=${USUARIO_15},password=${SENHA_15},rw //${SERVIDOR4} ${SERVER_VN_MODULO_COMPILADO}"

  return $?
}
if [ -e "${veianewIni}" ]
then
 . ${veianewIni}
else
  atualizaSenha
fi
montar15
if [ ${?} -ne "0" ]
then
  OPC=0
  while [ ${OPC} -ne 1 -a ${OPC} -ne 2 ]
  do
    echo -e  "NÃO FOI POSSIVEL MONTAR O CAMINHO //${SERVIDOR1} UTILIZANDO O COMANDO ABAIXO\n (${COMANDO1})"
    echo     "O QUE VOCE DESEJA FAZER?"
    echo     "1. PROSSEGUIR SEM MONTAR (utilizar versoes copiadas anteriormente)"
    echo     "2. ATUALIZAR USUARIO E SENHA DE ACESSO AO '192.168.0.15'"
    echo -ne "OPCAO: "
    read     OPC
    case ${OPC} in
      1)
        echo "PROSSEGUINDO ..."
      ;;
      2)
        atualizaSenha
        montar15
        [ $? -ne 0 ] && OPC=0
      ;;
      *)
        echo "DIGITE UMA OPCAO VALIDA!"
      ;;
    esac
  done
fi
# rsantos FIM

${COMANDO3}
IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
echo -e "${HOSTNAME}" "   -   " "${IP}" "   -   " "$(date +%d/%m/%y__%H:%M:%S)" "   -   " "${VERSION_VN}" >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVN/${HOSTNAME}.VNL;
sleep 3
umount ${SERVER_VN_SCRIPTS_VEIANEW}

rsync -uvt ${SERVER_VN_MANAGER}/php*.zip ${HTDOCS} &&

if [ -d ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" ] ; then
echo -e "Diretorio de Backup já existe."
else
mkdir ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" & chmod 777 ${SERVER_VN_MANAGER}/"$(date +%Y-%m)" &
fi

cd ${HTDOCS}/
for arquivo in *.ZIP
do
newname=$(basename ${arquivo} ZIP)zip
mv ${arquivo} ${newname}
done

 ${COMANDO2}
 cd  ${SERVER_VN_MODULOPHPPDV}
 for arquivo in *.zip.TEMP.zip
 do
 newname=$(basename ${arquivo} zip.TEMP.zip)zip
 mv ${arquivo} ${newname}
 done
 sleep 1 && umount ${SERVER_VN_MODULOPHPPDV}

cd ${HTDOCS}/

chown root.root ${HTDOCS}/*
chmod 777 ${HTDOCS}/*.zip

for file in *anager*.zip

do
   if [ ! "${file}" = `echo "${file}"|sed "s/ /_/g"` ]; then
   mv "${file}" `echo "${file}"|sed "s/ /_/g"`
   fi
done

find . -name "*anager*.zip"

ListaArquivos(){
if [ `find . -name '*anager*.zip' | wc -l` -gt 0 ]; then
clear; i=1

echo -e "#     ${Cor_Amarelo} OPÇÕES\t\b\b********************************  PACOTES  MANAGER  ********************************${Cor_Preto}"
CASE='case $opt in'
for arq in `ls -1tr *anager*.zip`
do
    echo -e "#\t\b\b\b\b$i    ${arq}"
    CASE="${CASE}
   $i) ${APACHE2}/bin/apachectl stop ; rm -rf ${HTDOCS}/*.zip.TEMP ; rsync -uv ${HTDOCS}/\"${arq}\" ${MANAGER} && unzip -oq ${MANAGER}/\"${arq}\" -d ${MANAGER} && touch ${HTDOCS}/\"${arq}.TEMP\" && echo -e '#\tEXTRACAO CONCLUIDA' && chown -R zanthus.zanthus * && chmod -R 777 * && ${APACHE2}/bin/apachectl start && mkdir ${MANAGER}/Logs && chown -R zanthus.zanthus ${MANAGER}/Logs/*; sleep 1 ;;"
    i=$((i+1))
done

CASE="${CASE}
   99) ${VEIANEW}/99.sh ;;
   98) ${APACHE2}/bin/apachectl stop ; sleep 1 && veianew ;;
   97) ${APACHE2}/bin/apachectl stop & ${APACHE2}/bin/apachectl start ; sleep 1 && veianew ;;

   89) php ${MANAGER}/servico/servicolinux.php5 start ; sleep 1 && veianew ;;
   88) php ${MANAGER}/servico/servicolinux.php5 stop ; pkill -9 php ; sleep 1 && veianew ;;
   87) php ${MANAGER}/servico/servicolinux.php5 stop ; pkill -9 php && php ${MANAGER}/servico/servicolinux.php5 start ; sleep 1 && veianew ;;

   79) node ${HTDOCS}/comet_zanthus/src/server-chat.js >> ${HTDOCS}/comet_zanthus/LOGS_NODE_$(date +%d%m%y).zlg & sleep 2 && echo -e NODE INICIADO ; sleep 1 && veianew ;;
   78) pkill node* & sleep 1 && echo -e NODE ENCERRADO ; sleep 1 && veianew ;;
   77) pkill node* & sleep 1 && echo -e NODE ENCERRADO &&  node ${HTDOCS}/comet_zanthus/src/server-chat.js & sleep 2 && echo -e NODE REINICIADO ; sleep 1 && veianew ;;

   69) php ${MANAGER}/servico/servicolinux.php5 start ; ${APACHE2}/bin/apachectl start ; sleep 1 && veianew ;;
   68) sudo php ${MANAGER}/servico/servicolinux.php5 stop ; sudo pkill -9 php ; sudo ${APACHE2}/bin/apachectl stop ; sleep 1 && veianew ;;
   67) php ${MANAGER}/servico/servicolinux.php5 stop ; pkill -9 php && ${APACHE2}/bin/apachectl stop && php ${MANAGER}/servico/servicolinux.php5 start && ${APACHE2}/bin/apachectl start ; sleep 1 && veianew ;;

   66) ${APACHE2}/bin/apachectl start ; sleep 1; php ${MANAGER}/servico/servicolinux.php5 start ; node ${HTDOCS}/comet_zanthus/src/server-chat.js >> ${HTDOCS}/comet_zanthus/LOGS_NODE_$(date +%d%m%y).ZL1 & sleep 2 && echo -e NODE INICIADO ; sleep 1 && veianew ;;
   65) sudo php ${MANAGER}/servico/servicolinux.php5 stop ; sudo pkill -9 php ; sudo ${APACHE2}/bin/apachectl stop ; pkill node* & sleep 1 && echo -e NODE ENCERRADO ; sleep 1 && veianew ;;
   64) sudo php ${MANAGER}/servico/servicolinux.php5 stop ; sudo pkill -9 php ; sudo ${APACHE2}/bin/apachectl stop ; pkill node* & sleep 1 && echo -e NODE ENCERRADO ; sleep 2 ; ${APACHE2}/bin/apachectl start ; sleep 1; php ${MANAGER}/servico/servicolinux.php5 start ; node ${HTDOCS}/comet_zanthus/src/server-chat.js >> ${HTDOCS}/comet_zanthus/LOGS_NODE_$(date +%d%m%y).ZL1 & sleep 2 && echo -e NODE INICIADO ; sleep 1 && veianew ;;

   59) rm -rf ${MANAGER}/* && rm -rf ${HTDOCS}/*.zip.TEMP; cp -rf ${HTDOCS}/certificados ${MANAGER}/ && cp -rf ${HTDOCS}/ZMWSInfo_COMLOG.* ${MANAGER}/ZMWSInfo.ini ; sleep 1 && veianew ;;
   599) rm -rf ${HTDOCS}/php_*.zip && sleep 1 && veianew ;;
   58) cp -rf ${HTDOCS}/ZMWSInfo_COMLOG.* ${MANAGER}/ZMWSInfo.ini ; sleep 1 ; veianew ;;
   57) cp -rf ${HTDOCS}/ZMWSInfo_SEMLOG.* ${MANAGER}/ZMWSInfo.ini ; sleep 1 ; veianew ;;
   56) cp -rf ${HTDOCS}/ZMWSInfo_COMLOGFULL.* ${MANAGER}/ZMWSInfo.ini ; sleep 1 && veianew ;;
   55) cp -rf ${MANAGER}/certificados/* ${HTDOCS}/certificados/ ; sleep 1 && veianew ;;
   54) sudo find ${MANAGER}/ -iname '*.zlg' -exec rm -rf {} \; ; sudo find ${MANAGER}/ -iname 'mirage_*.log' -exec rm -rf {} \; ; sleep 1 && veianew ;;
   53) sudo find ${HTDOCS}/ -iname '*.zlg' -exec rm -rf {} \; ; sudo find ${HTDOCS}/ -iname 'mirage_*.log' -exec rm -rf {} \; ; sleep 1 && veianew ;;
   52) sudo umount ${SERVER_VN_MODULOPHPPDV}/; sleep 5 ; ${COMANDO2} ; cd ${HTDOCS}/modulo_compilado; sleep 5; sudo php equalizar_pastas.php ; sudo zip -r ${HTDOCS}/Modulo_$(cd ${HTDOCS}/; ls *.zip.TEMP).zip * ; cp Modulo_$(cd ${HTDOCS}/; ls *.zip.TEMP).zip ${SERVER_VN_MODULOPHPPDV}/ ; umount $moduloPHPPDV/; sleep 1 && veianew ;;
   51) sudo touch /tmp/__check_js_errors.zan /tmp/__consultoria__.zan && chmod 755 /tmp/__check_js_errors.zan /tmp/__consultoria__.zan ; sleep 1 ; veianew ;;
   50) sudo touch /tmp/__debug_claz.zan && chmod 755 /tmp/__debug_claz.zan ; sleep 1 ; veianew ;;
   49) rm -rf /tmp/__check_js_errors.zan  /tmp/__consultoria__.zan /tmp/__debug_claz.zan ; sleep 1 ; veianew ;;
   48) sudo chmod -R 777 ${MANAGER}/Arquivos/* &&  chown -R root.root ${MANAGER}/Arquivos/*  ; sleep 1 ; veianew ;;

   07) wget -N -v --tries=1 -P ${VEIANEW}/veianew_estruturado ftp://${VEIANEW}/veianew_estruturado ;;
   06) echo -e 'Aguarde, conectando no ftp.zanthus.com.br';  echo -e 'Atualizando bibliotecas para o PATH_COMUM!!!'; sleep 3 && wget -N -v --tries=2 -P ${PATH_COMUM}/so/ ftp://${FTP_COMPLEMENTARES}/so/* ; wget -N -v --tries=2 -P ${PATH_COMUM}/so_co5 ftp://${FTP_COMPLEMENTARES}/so_co5/* ; wget -N -v --tries=2 -P ${PATH_COMUM}/so_r64 ftp://${FTP_COMPLEMENTARES}/so_r64/* ; wget -N -v --tries=2 -P ${PATH_COMUM}/so_u64 ftp://${FTP_COMPLEMENTARES}/so_u64/* ; wget -N -v --tries=2 -P ${PATH_COMUM}/so_ubu ftp://${FTP_COMPLEMENTARES}/so_ubu/* ; sleep 1 && veianew ;;
   05) umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* && umount ${SERVER_VN}/* ;;
   04) /etc/init.d/memcached restart && sleep 1 ; echo -e "" ; echo -e "" ;  echo -e 'Reinicialização do MEMCACHED concluida com sucesso!!!' ; echo -e "" ; echo -e "" ; sleep 3 ; veianew ;;
   03) rsync -uv /Zanthus/Zeus/PATH_COMUM/so_r64/* /usr/src/libs_zanthus ; ldconfig ; sleep 1 ; veianew ;;
   02) ${COMANDO4} && sleep 4 ; mv -f  ${HTDOCS}/modulo_compilado ${HTDOCS}/modulo_compilado_OLD ; sleep 3 ; mkdir ${HTDOCS}/modulo_compilado ; chmod -R 777 ${HTDOCS}/modulo_compilado ; rsync -ravzpt ${SERVER_VN_MODULO_COMPILADO}/* ${HTDOCS}/modulo_compilado/ && umount ${SERVER_VN_MODULO_COMPILADO}/ && rm -rf ${HTDOCS}/modulo_compilado_OLD && sleep 1 && echo -e "" ; echo -e "" ; echo -e 'Atualização do Modulo_Compilado concluída com sucesso!!!' ; echo -e "" ; echo -e "" ; sleep 2 ; veianew ;;
   01) ${VEIANEW}/01.sh ;;
   00) umount ${SERVER_VN}/* && exit ;;

   001) rm -rf /bin/veianew_OLD ; cp /bin/veianew /bin/veianew_OLD ; ${COMANDO3} ; sleep 3 ; rsync -uv ${SERVER_VN_SCRIPTS_VEIANEW}/veianew_ATUALIZADO_BETA /bin/veianew_ATUALIZADO_BETA ; echo -e "${HOSTNAME}" >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVERSION_veianew.VNL; date >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVERSION_veianew.VNL; echo -e "${VERSION_VN}" >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVERSION_veianew.VNL; echo -e "-----------------------------" >> ${SERVER_VN_SCRIPTS_VEIANEW}/LOGVERSION_veianew.VNL; umount ${SERVER_VN_SCRIPTS_VEIANEW}/ ; mv /bin/veianew_ATUALIZADO_BETA /bin/veianew && sleep 1 ; echo -e "" ; echo -e "" ;  echo -e 'Atualização do veianew BETA concluida com sucesso!!!' ; echo -e "" ; echo -e "" ;;
   BKP) ${COMANDO1} ; ${COMANDO3}; sleep 3 &&  rsync -uv ${SERVER_VN_SCRIPTS_VEIANEW}/BKP_manager.sh ${MANAGER}/BKP_manager.sh ; chmod -x ${MANAGER}/BKP_manager.sh && ${MANAGER}/BKP_manager.sh ; sleep 5 ; rm ${MANAGER}/BKP_manager.sh ; umount ${MANAGER}/ ; sleep 2 ; veianew ;;
   BKPMODULO) ${COMANDO1} ; ${COMANDO3}; sleep 3 &&  rsync -uv ${SERVER_VN_SCRIPTS_VEIANEW}/BKP_moduloPHPPDV.sh ${SERVER_VN_MODULOPHPPDV}/BKP_moduloPHPPDV.sh ; chmod -x ${SERVER_VN_MODULOPHPPDV}/BKP_moduloPHPPDV.sh && ${SERVER_VN_MODULOPHPPDV}/BKP_moduloPHPPDV.sh ; sleep 5 ; rm ${SERVER_VN_MODULOPHPPDV}/BKP_moduloPHPPDV.sh ; umount ${SERVER_VN_MODULOPHPPDV}/ ; sleep 2 ; veianew ;;
   *) echo 'OPÇÃO INVÁLIDA! TENTE NOVAMENTE'; sleep 2; clear; ListaArquivos;;
esac"

echo -e ""
echo -e "#\t${Cor_Amarelo}\b\b\b\bMANAGER EM USO:" *.zip.TEMP
echo -e "${Cor_Preto}"
#echo -e "\t\t***** APACHE *****                           ***** MIRAGE *****                  ***** NODE *****"
echo -e "#\t\b\b\b\b99    START     APACHE               89    START     MIRAGE              79    START     NODE"
echo -e "#\t\b\b\b\b98    STOP      APACHE               88    STOP      MIRAGE              78    STOP      NODE"
echo -e "#\t\b\b\b\b97    RESTART   APACHE               87    RESTART   MIRAGE              77    RESTART   NODE"
echo -e ""
#echo -e "\t\t***** APACHE / MIRAGE *****                                  ***** APACHE / MIRAGE / NODE *****"
echo -e "#\t\b\b\b\b69    START     APACHE e MIRAGE                          66   START     APACHE, MIRAGE e NODE"
echo -e "#\t\b\b\b\b68    STOP      APACHE e MIRAGE                          65   STOP      APACHE, MIRAGE e NODE"
echo -e "#\t\b\b\b\b67    RESTART   APACHE e MIRAGE                          64   RESTART   APACHE, MIRAGE e NODE"
echo -e ""
echo -e "#\t\b\b\b\b59    LIMPAR DIRETÓRIO MANAGER + COPIAR CERTIFICADO + ZMWSInfo"
echo -e "#\t\b\b\b\b599   LIMPAR PACOTES MANAGER DO 'HTDOCS'"
echo -e "#\t\b\b\b\b58    ZMWSInfo COM LOG"
echo -e "#\t\b\b\b\b57    ZMWSInfo SEM LOG"
echo -e "#\t\b\b\b\b56    ZMWSInfo COM LOG FULL                                 08    RESERVADO!!!"
echo -e "#\t\b\b\b\b55    FAZER BACKUP CERTIFICADO                              07    RESERVADO!!!"
echo -e "#\t\b\b\b\b54    LIMPAR LOGS ../MANAGER                                06    WGET BIBLIOTECAS FTP > PATH_COMUM"
echo -e "#\t\b\b\b\b53    LIMPAR LOGS ../HTDOCS                                 05    FORCE UMOUNT"
echo -e "#\t\b\b\b\b52    GERAR MODULOPHPPDV                                    04    REINICIAR MEMCACHED"
echo -e "#\t\b\b\b\b51    ATIVAR 'INSPEC_ELEMENTO' E 'CHECK_JS'                 03    ATUALIZAR BIBLIOTECA"
echo -e "#\t\b\b\b\b50    ATIVAR 'DEBUG_CLAZ'                                   02    ATUALIZAR Modulo_Compilado"
echo -e "#\t\b\b\b\b49    DESATIVAR INSPEC_ELEMENTO CHECK_JS DEBUG_CLAZ         01    ATUALIZAR VEIANEW"
echo -e "#\t\b\b\b\b48    PERMISSÃO DIRETORIO 'ARQUIVOS'                        00    SAIR"
echo -e "#\t\b\b\b\b                                                                              ${Cor_FundoCinza} ${Cor_Vermelho} ${VERSION_VN} ${Cor_Preto}"
echo -ne "#${Cor_VerdeClaro}   INFORME A OPÇÃO DESEJADA: "
read -p "" opt
echo -e "${Cor_Preto}"
eval "${CASE}"

else
clear
echo -e "#\n#\n#\t NÃO HA PACOTES DO MANAGER DISPONIVEIS PARA EXTRAÇÃO\n#\n#"
sleep 2
clear
fi
}

ListaArquivos
